server:
  port: 8082
  tomcat:
    uri-encoding: utf-8
netty:
  port: 6666
spring:
  http:
    encoding:
      charset: UTF-8
  profiles:
    active: test
  banner:
    charset: UTF-8
admin:
  username: guest
  password: guest

spring:
  application:
    name: log4j2

logging:
  path: ./logs
  level:
    root: info