server:
  port: 8082
  tomcat:
    uri-encoding: utf-8
netty:
  port: 6666
spring:
  http:
    encoding:
      charset: UTF-8
  banner:
    charset: UTF-8
  application:
    name: log4j2

admin:
  username: guest
  password: guest

logging:
  path: ./logs
  level:
    root: info