server:
  port: 8082
  tomcat:
    uri-encoding: utf-8
spring:
  http:
    encoding:
      charset: UTF-8
  banner:
    charset: UTF-8
  application:
    name: galaxy-message

logging:
  path: ./logs
  level:
    root: info